
define(function (require, exports, module) {
    "use strict";

    var CommandManager = brackets.getModule("command/CommandManager"),
        Menus          = brackets.getModule("command/Menus"),
        EditorManager  = brackets.getModule("editor/EditorManager");


    // Function to run when the menu item is clicked
    function NewJect_HTML() {
          
      var editor = EditorManager.getCurrentFullEditor();
      if (editor) {
        var insertionPos = editor.getCursorPos();
        editor.document.batchOperation(function () {
        var htmlcontent =  '<!DOCTYPE html>\n<html>\n'+
        '<head>\n'+
        '<meta charset="utf-8">\n'+
        '<meta http-equiv="X-UA-Compatible" content="IE=edge">\n'+
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'+
        '<meta name="description" content="">\n'+
        '<meta name="author" content="">\n\r'+
        '<title>New HMTL document by NewJect</title>\n\r'+
        '</head>\n'+
        '<body>\n\r'+
        '<div>\n'+
        '<h3>this is new html document generated by newject extention</h3>\n'+
        '</div>\n\r'+
        '</body>\n'+
        '</html>';
          editor.document.replaceRange(htmlcontent, insertionPos);
        });
      }
 
    }
    function NewJect_jquery(){
             var editor = EditorManager.getCurrentFullEditor();
      if (editor) {
        var insertionPos = editor.getCursorPos();
        editor.document.batchOperation(function () {
        var jquerycontent =  '$("document").ready(function(){\n\r'+
        '//Your code here\n\r'+'});';
          editor.document.replaceRange(jquerycontent, insertionPos);
        });
      } 
    }


    var NewjectHTML = "htmlskeleton.newject";
    CommandManager.register("HTML5", NewjectHTML, NewJect_HTML);
    var NewjectJQUERY = "jqueryskeleton.newject";
    CommandManager.register("JQUERY", NewjectJQUERY, NewJect_jquery);

    Menus.addMenu('NewJect','newject.main');
    var menu = Menus.getMenu('newject.main');
    menu.addMenuItem(NewjectHTML);
    menu.addMenuItem(NewjectJQUERY);


});
